biocypher:
  strict_mode: true
  schema_config_path: config/schema_config.yaml

neo4j:
  database_name: neo4j
  delimiter: '\t'
  quote_character: '@'
  array_delimiter: '|'
  skip_bad_relationships: true